#!/usr/bin/env bash
set -e

eval_tag=left_vae_scratch9_joint_pos_gaussian_online_pb_beta10_m16_v1
demo_tag=left_vae_scratch9_joint_pos_gaussian_online_pb_beta10_m16_v1
method_name=left_vae_scratch9_joint_pos_gaussian_online_pb
checkpoint_prefix=robo_manip_baselines/checkpoint/DiffusionPolicy/DatasetMujocoUR5eLiftingi_LeftVaeScratch9dim_JointPos_GaussianOnlinePB_beta10_m16_20260821_v1
wp4_checkpoint=robo_manip_baselines/checkpoint/WrenchPredictor4/DatasetMujocoUR5eLiftingi_LeftVaeScratch9dim_JointPos_GaussianStudy_20260821_v1/policy_best.ckpt
image_vae_checkpoint=robo_manip_baselines/checkpoint/ImageVAE/DatasetMujocoUR5eLiftingi_LeftVaeScratch9dim_GaussianStudy_20260821_v1/final_model
image_vae_camera_name=left

source scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiGaussian/rollout_gaussian_image_pb_common.sh
