#!/usr/bin/env bash
set -e

eval_tag=hand_vae_scratch9_eef_pose_gaussian_online_pb_beta10_m16_v1
demo_tag=hand_vae_scratch9_eef_pose_gaussian_online_pb_beta10_m16_v1
method_name=hand_vae_scratch9_eef_pose_gaussian_online_pb
checkpoint_prefix=robo_manip_baselines/checkpoint/DiffusionPolicy/DatasetMujocoUR5eLiftingi_HandVaeScratch9dim_EefPose_GaussianOnlinePB_beta10_m16_20260821_v1
wp4_checkpoint=robo_manip_baselines/checkpoint/WrenchPredictor4/DatasetMujocoUR5eLiftingi_HandVaeScratch9dim_EefPose_GaussianStudy_20260821_v1/policy_best.ckpt
image_vae_checkpoint=robo_manip_baselines/checkpoint/ImageVAE/DatasetMujocoUR5eLiftingi_HandVaeScratch9dim_GaussianStudy_20260821_v1/final_model
image_vae_camera_name=hand

source scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiGaussian/rollout_gaussian_image_pb_common.sh
