#!/usr/bin/env bash
set -e

# Run the complete beta=2.0 training and rollout pipeline from the repository root.
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9Wp4JointPosDpEefPoseBeta2/train_left_image_vae_wp4.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9Wp4JointPosDpEefPoseBeta2/prepare_datasets.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9Wp4JointPosDpEefPoseBeta2/train_DP_online_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9Wp4JointPosDpEefPoseBeta2/train_constant_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9Wp4JointPosDpEefPoseBeta2/rollout_DP_online_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9Wp4JointPosDpEefPoseBeta2/rollout_constant_pb_seed42_52_62.sh
