#!/usr/bin/env bash
set -e

# Run the DP training and rollout pipeline with the existing hand-camera
# ImageVAE 9D and WP4 checkpoints.
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingi/prepare_datasets.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingi/train_baseline_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingi/train_DP_online_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingi/train_constant_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingi/prepare_validation_online_pb.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingi/rollout_baseline_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingi/rollout_DP_online_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingi/rollout_constant_pb_seed42_52_62.sh
