#!/usr/bin/env bash
set -e

# Run the complete training and rollout pipeline from the repository root.
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/train_left_image_vae_wp4.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/prepare_datasets.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/train_baseline_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/train_DP_online_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/train_constant_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/prepare_validation_online_pb.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/rollout_baseline_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/rollout_DP_online_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImage/DatasetUR5eLiftingiLeftScratchVAE9/rollout_constant_pb_seed42_52_62.sh
