#!/usr/bin/env bash
set -e

# Run the DP training and rollout pipeline with the existing left-camera
# ImageVAE 9D and WP4 checkpoints.
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingiLeftScratchVAE9/prepare_datasets.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingiLeftScratchVAE9/train_baseline_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingiLeftScratchVAE9/train_DP_online_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingiLeftScratchVAE9/train_constant_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingiLeftScratchVAE9/prepare_validation_online_pb.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingiLeftScratchVAE9/rollout_baseline_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingiLeftScratchVAE9/rollout_DP_online_pb_seed42_52_62.sh
bash scripts/FutureImagination/LiftingImageDpImage/DatasetUR5eLiftingiLeftScratchVAE9/rollout_constant_pb_seed42_52_62.sh
